// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"Fullscreen","status":false,"description":"Starts the game in fullscreen","parameters":{}},
{"name":"Galv_ScreenButtons","status":true,"description":"(v.1.3) Show buttons on screen that can be touched or clicked.","parameters":{"Precache Buttons":"BtnUp,BtnDown,BtnRight,BtnLeft,BtnOk,BtnCancel","Disable Mouse Move":"true","Button Fade":"30"}},
{"name":"$MUSH_MenuOptionScreenResolution_P1","status":true,"description":"[v.1.03] Adds the screen resolution option.","parameters":{"Resolution Command Name":"Screen Resolution","Resolution Options":"[ [816, 624], [1280, 720], [1366, 768], [1920, 1080] ]","Scale Graphics":"true","Reposition Sprites":"true"}}
];
